export const content: string;
export const header: string;
export const headerText: string;
export const weekContainer: string;
export const chevron: string;
export const chevronRight: string;
export const chevronLeft: string;
export const left: string;
export const right: string;
