const prefix = (text: string) => `APPOINTMENT_EDITOR.${text}`;

const APPOINTMENT_EDITOR_CLOSE = prefix('CLOSE');
const APPOINTMENT_EDITOR_UPDATE_START = prefix('UPDATE_START');
const APPOINTMENT_EDITOR_UPDATE_END = prefix('UPDATE_END');
const APPOINTMENT_EDITOR_UPDATE_TITLE = prefix('UPDATE_TITLE');
const APPOINTMENT_EDITOR_SAVE = prefix('SAVE');
const APPOINTMENT_EDITOR_DELETE = prefix('DELETE');

export default {
  APPOINTMENT_EDITOR_CLOSE,
  APPOINTMENT_EDITOR_UPDATE_START,
  APPOINTMENT_EDITOR_UPDATE_END,
  APPOINTMENT_EDITOR_UPDATE_TITLE,
  APPOINTMENT_EDITOR_SAVE,
  APPOINTMENT_EDITOR_DELETE
};
