export const content: string;
export const background: string;
export const modal: string;
export const header: string;
export const title: string;
export const close: string;
export const form: string;
export const datetime: string;
export const save: string;
